name: Build Core 3.1

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * 5"
  workflow_dispatch:
  
jobs:
  build:
    name: build to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0      
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: 'src/SapCo2/'
      run: dotnet restore sapco2
    - name: Build
      working-directory: 'src/SapCo2/'
      run: dotnet build sapco2 --configuration Release --no-restore
