name: Multi Build And Test ( Net5.0, Core3.1, Core2.1 )

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * 5"
  workflow_dispatch:
  
jobs:
  build:
    name: build to staging
    runs-on: windows-latest
    continue-on-error: true
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - dotnet: '5.0.100'
            name: 'net5.0'
            libraryName: 'net5.0'
          - dotnet: '3.1.404'
            name: 'netcoreapp3.1'
            libraryName: 'netstandard2.1'
          - dotnet: '2.1.811'
            name: 'netcoreapp2.1'
            libraryName: 'netstandard2.0'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: ${{ matrix.dotnet }}    
    - name: Install ${{ matrix.dotnet }} dependencies
      working-directory: './src/SapCo2/SapCo2'
      run: dotnet restore SapCo2.csproj --no-dependencies -verbosity d
    - name: Build ${{ matrix.dotnet }} project
      working-directory: './src/SapCo2/SapCo2'
      run: dotnet build SapCo2.csproj --configuration Release --no-restore -f ${{ matrix.libraryName }}
    - name: Install ${{ matrix.dotnet }} Test dependencies
      working-directory: './src/SapCo2/Tests/SapCo2.Test'
      run: dotnet restore SapCo2.Test.csproj --no-dependencies -verbosity d
    - name: Test ${{ matrix.dotnet }} project
      working-directory: './src/SapCo2/Tests/SapCo2.Test'
      run: dotnet test SapCo2.Test.csproj --configuration Release --no-restore -f ${{ matrix.libraryName }}
