name: Build Core 5.0

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * 5"
  workflow_dispatch:
  
jobs:
  build:
    name: build to staging
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        include:
          - dotnet: '5.0.100'
            name: 'net5.0'
          - dotnet: '3.1.404'
            name: 'netcoreapp3.1'
          - dotnet: '2.1.818'
            name: 'netcoreapp2.1'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: ${{ matrix.dotnet }}    
    - name: Install ${{ matrix.dotnet }} dependencies
      working-directory: './src/SapCo2'
      run: dotnet restore sapco2
    - name: Build ${{ matrix.dotnet }} project
      working-directory: './src/SapCo2'
      run: dotnet build sapco2 --configuration Release --no-restore -f ${{ matrix.name }}
